### ISSUE TITLE
Movement bug

### ISSUE THREAD

**Issue by Rirush** [CatMB/ffffff-java#1]
If use more than one button (WASD) and then release one then hero will stop.

Ways to fix:
* Fix bug (if pressed more than 1 button -> ignore all excluding first) and use 4-direction movement
* Fix bug (use two buttons) and use 8-direction movement

**Comment by mefest** [comment]
@Racc-oon Это что?

**Comment by Rirush** [comment]
@mefest Баг.

**Comment by Rirush** [comment]
Fixed
